// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Conversation struct {
	ID        int64
	GroupID   pgtype.Int8
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type ConversationMember struct {
	ConversationID    int64
	UserID            int64
	LastReadMessageID pgtype.Int8
	JoinedAt          pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
}

type Message struct {
	ID             int64
	ConversationID int64
	SenderID       pgtype.Int8
	MessageText    string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}
