// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addConversationMember = `-- name: AddConversationMember :one
INSERT INTO conversation_members (conversation_id, user_id)
VALUES ($1, $2)
RETURNING conversation_id, user_id, last_read_message_id, joined_at, deleted_at
`

type AddConversationMemberParams struct {
	ConversationID int64
	UserID         int64
}

func (q *Queries) AddConversationMember(ctx context.Context, arg AddConversationMemberParams) (ConversationMember, error) {
	row := q.db.QueryRow(ctx, addConversationMember, arg.ConversationID, arg.UserID)
	var i ConversationMember
	err := row.Scan(
		&i.ConversationID,
		&i.UserID,
		&i.LastReadMessageID,
		&i.JoinedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (group_id)
VALUES ($1)
RETURNING id, group_id, created_at, updated_at, deleted_at
`

func (q *Queries) CreateConversation(ctx context.Context, groupID pgtype.Int8) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation, groupID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (conversation_id, sender_id, message_text)
SELECT $1, $2, $3
FROM conversation_members
WHERE conversation_id = $1
  AND user_id = $2
  AND deleted_at IS NULL
RETURNING id, conversation_id, sender_id, message_text, created_at, updated_at, deleted_at
`

type CreateMessageParams struct {
	ConversationID int64
	SenderID       pgtype.Int8
	MessageText    string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.ConversationID, arg.SenderID, arg.MessageText)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.MessageText,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getConversationMembers = `-- name: GetConversationMembers :many
SELECT cm2.user_id
FROM conversation_members cm1
JOIN conversation_members cm2
  ON cm2.conversation_id = cm1.conversation_id
WHERE cm1.user_id = $2
  AND cm2.conversation_id = $1
  AND cm2.user_id <> $2
  AND cm2.deleted_at IS NULL
`

type GetConversationMembersParams struct {
	ConversationID int64
	UserID         int64
}

func (q *Queries) GetConversationMembers(ctx context.Context, arg GetConversationMembersParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, getConversationMembers, arg.ConversationID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessages = `-- name: GetMessages :many
SELECT m.id, m.conversation_id, m.sender_id, m.message_text, m.created_at, m.updated_at, m.deleted_at
FROM messages m
JOIN conversation_members cm 
  ON cm.conversation_id = m.conversation_id
WHERE m.conversation_id = $1
  AND cm.user_id = $2
  AND m.deleted_at IS NULL
ORDER BY m.created_at ASC
LIMIT $3 OFFSET $4
`

type GetMessagesParams struct {
	ConversationID int64
	UserID         int64
	Limit          int32
	Offset         int32
}

func (q *Queries) GetMessages(ctx context.Context, arg GetMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getMessages,
		arg.ConversationID,
		arg.UserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.MessageText,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserConversations = `-- name: GetUserConversations :many
SELECT 
    c.id AS conversation_id,
    c.group_id,
    c.created_at,
    c.updated_at,
    cm2.user_id AS member_id
FROM conversations c
JOIN conversation_members cm1
    ON cm1.conversation_id = c.id
    AND cm1.user_id = $1
    AND cm1.deleted_at IS NULL
JOIN conversation_members cm2
    ON cm2.conversation_id = c.id
    AND cm2.user_id <> $1
    AND cm2.deleted_at IS NULL
WHERE c.deleted_at IS NULL
AND (
    ($2 IS NULL AND c.group_id IS NULL)
    OR ($2 IS NOT NULL AND c.group_id = $2)
)
ORDER BY c.updated_at DESC
LIMIT $3 OFFSET $4
`

type GetUserConversationsParams struct {
	UserID  int64
	Column2 interface{}
	Limit   int32
	Offset  int32
}

type GetUserConversationsRow struct {
	ConversationID int64
	GroupID        pgtype.Int8
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	MemberID       int64
}

func (q *Queries) GetUserConversations(ctx context.Context, arg GetUserConversationsParams) ([]GetUserConversationsRow, error) {
	rows, err := q.db.Query(ctx, getUserConversations,
		arg.UserID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserConversationsRow{}
	for rows.Next() {
		var i GetUserConversationsRow
		if err := rows.Scan(
			&i.ConversationID,
			&i.GroupID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemberID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteConversationMember = `-- name: SoftDeleteConversationMember :one
UPDATE conversation_members cm_target
SET deleted_at = NOW()
FROM conversation_members cm_actor
WHERE cm_target.conversation_id = $1
  AND cm_target.user_id = $2
  AND cm_target.deleted_at IS NULL
  AND cm_actor.conversation_id = $1
  AND cm_actor.user_id = $3
  AND cm_actor.deleted_at IS NULL
RETURNING cm_target.conversation_id, cm_target.user_id, cm_target.last_read_message_id, cm_target.joined_at, cm_target.deleted_at
`

type SoftDeleteConversationMemberParams struct {
	ConversationID int64
	UserID         int64
	UserID_2       int64
}

func (q *Queries) SoftDeleteConversationMember(ctx context.Context, arg SoftDeleteConversationMemberParams) (ConversationMember, error) {
	row := q.db.QueryRow(ctx, softDeleteConversationMember, arg.ConversationID, arg.UserID, arg.UserID_2)
	var i ConversationMember
	err := row.Scan(
		&i.ConversationID,
		&i.UserID,
		&i.LastReadMessageID,
		&i.JoinedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateLastReadMessage = `-- name: UpdateLastReadMessage :one
UPDATE conversation_members cm
SET last_read_message_id = $3
WHERE cm.conversation_id = $1
  AND cm.user_id = $2
  AND cm.deleted_at IS NULL
RETURNING conversation_id, user_id, last_read_message_id, joined_at, deleted_at
`

type UpdateLastReadMessageParams struct {
	ConversationID    int64
	UserID            int64
	LastReadMessageID pgtype.Int8
}

func (q *Queries) UpdateLastReadMessage(ctx context.Context, arg UpdateLastReadMessageParams) (ConversationMember, error) {
	row := q.db.QueryRow(ctx, updateLastReadMessage, arg.ConversationID, arg.UserID, arg.LastReadMessageID)
	var i ConversationMember
	err := row.Scan(
		&i.ConversationID,
		&i.UserID,
		&i.LastReadMessageID,
		&i.JoinedAt,
		&i.DeletedAt,
	)
	return i, err
}
