// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddConversationMember(ctx context.Context, arg AddConversationMemberParams) (ConversationMember, error)
	CreateConversation(ctx context.Context, groupID pgtype.Int8) (Conversation, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	GetConversationMembers(ctx context.Context, arg GetConversationMembersParams) ([]int64, error)
	GetMessages(ctx context.Context, arg GetMessagesParams) ([]Message, error)
	GetUserConversations(ctx context.Context, arg GetUserConversationsParams) ([]GetUserConversationsRow, error)
	SoftDeleteConversationMember(ctx context.Context, arg SoftDeleteConversationMemberParams) (ConversationMember, error)
	UpdateLastReadMessage(ctx context.Context, arg UpdateLastReadMessageParams) (ConversationMember, error)
}

var _ Querier = (*Queries)(nil)
